#!/usr/bin/env bash                                                                                                         
# configure web-02 to be identical to web-01                                                                                
# The name of the custom HTTP header must be X-Served-By                                                                    
# The value of the custom HTTP header must be the hostname of the server Nginx is running on                                
#this command will add server name to the configuration file                                                                
#sudo sed -i 's/server_name _;.*/server_name _;\n\tadd_header X-Served-By \$hostname;/' /etc/nginx/sites-enabled/default    
                                                                                                                            
                                                                                                                            
server_config=\                                                                                                             
"server {                                                                                                                   
        listen 80 default_server;                                                                                           
        listen [::]:80 default_server;                                                                                      
        root /var/www/html;                                                                                                 
        index index.html index.htm index.nginx-debian.html;                                                                 
        server_name _;                                                                                                      
        add_header X-Served-By \$hostname;                                                                                  
        location / {                                                                                                        
                try_files \$uri \$uri/ =404;                                                                                
        }                                                                                                                   
        if (\$request_filename ~ redirect_me){                                                                              
                rewrite ^ https://youtube.com permanent;                                                                    
        }                                                                                                                   
        error_page 404 /404.html;                                                                                           
        location = /404.html {                                                                                              
                internal;                                                                                                   
        }                                                                                                                   
}"                                                                                                                          
echo "$server_config" > /etc/nginx/sites-enabled/default                                                                    
sudo service nginx restart    
