#!/usr/bin/env bash

# Configure UFW firewall to block all incoming traffic
#+ except for TCP 22, 443, 80

sudo apt-get update
sudo apt install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
